### ISSUE TITLE
number type issues

### ISSUE THREAD

**Issue by jdeck88** [futres/FutresAPI#4]
When loading data into ES it is vital that numbers are actually numbers... so we can perform number type queries.  So, we need to filter results.  this is done in python like:

thisDF = thisDF[thisDF.measurementValue == isinstance(thisDF.measurementValue,(int,float))]

only returning values in dataframe that are ints or longs..  this, however, removes about 200,000 vertnet records and including many of the weight-based measurements... need to research this.  
Consequently, this limits the number of traits and units appearing in the interface....

**Comment by robgur** [comment]
We need to fix this big time. I don't understand why this is an issue, though.

**Comment by jdeck88** [comment]
This is fixed with recent addition of data_pruning class where we remove any data that doesn't comply with standards and report it.  This gives us a way to both report and resolve data that doesn't work in interface.
